services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      ports:
        - 5432:5432
  app:
    build: .
    ports:
      - 8123:8000
    depends_on:
      - db