services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - '1111:5432'
  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db